language: node_js
node_js:
  - "0.12"
env:
  - NODE_ENV=development

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # default: false
